/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view;

import controller.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
/**
 *
 * @author purcell
 */
public class MainFrame extends javax.swing.JFrame{
    private KaryawanController karyawanController;
    private PenggajianController penggajianController;
    
    public MainFrame() {
        initComponents(); // Auto-generated by NetBeans
        initControllers();
        loadData();
        setupListeners();
        setupFormVisibility();
    }
    
    private void initControllers() {
        karyawanController = new KaryawanController(this);
        penggajianController = new PenggajianController(this);
    }
    
    private void loadData() {
        karyawanController.loadDataKeTabel();
    }
    
    private void setupListeners() {
        // Tombol CRUD
        btnTambah.addActionListener(e -> tambahKaryawan());
        btnUpdate.addActionListener(e -> updateKaryawan());
        btnHapus.addActionListener(e -> hapusKaryawan());
        btnRefresh.addActionListener(e -> loadData());
        btnCari.addActionListener(e -> cariKaryawan());
        
        // Tombol Penggajian (MULTITHREAD)
        btnHitungGaji.addActionListener(e -> {
            txtAreaHasil.setText(""); // Clear previous
            penggajianController.hitungGajiSemuaKaryawan();
        });
        
        // Event klik tabel
        tblKaryawan.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = tblKaryawan.getSelectedRow();
                if (row >= 0) {
                    isiFormDariTabel(row);
                }
            }
        });
        
        // Combo box listener untuk menampilkan field sesuai jenis
        cmbJenisKontrak.addActionListener(e -> setupFormVisibility());
    }
    
    private void setupFormVisibility() {
        if (cmbJenisKontrak.getSelectedItem().equals("Tetap")) {
            lblGajiPokok.setVisible(true);
            txtGajiPokok.setVisible(true);
            lblBonus.setVisible(true);
            txtBonus.setVisible(true);
            lblJamKerja.setVisible(false);
            txtJamKerja.setVisible(false);
        } else {
            lblGajiPokok.setVisible(false);
            txtGajiPokok.setVisible(false);
            lblBonus.setVisible(false);
            txtBonus.setVisible(false);
            lblJamKerja.setVisible(true);
            txtJamKerja.setVisible(true);
        }
    }
    
    private void tambahKaryawan() {
        if (validateInput()) {
            double gajiPokok = 0, bonus = 0;
            int jamKerja = 0;
            
            if (cmbJenisKontrak.getSelectedItem().equals("Tetap")) {
                gajiPokok = Double.parseDouble(txtGajiPokok.getText());
                bonus = Double.parseDouble(txtBonus.getText());
            } else {
                jamKerja = Integer.parseInt(txtJamKerja.getText());
            }
            
            boolean success = karyawanController.tambahKaryawan(
                txtNip.getText(),
                txtNama.getText(),
                cmbJenisKontrak.getSelectedItem().toString(),
                gajiPokok, bonus, jamKerja
            );
            
            if (success) {
                clearForm();
                loadData();
            }
        }
    }
    
    private void updateKaryawan() {
        int row = tblKaryawan.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diupdate!");
            return;
        }
        
        int id = (int) tblKaryawan.getValueAt(row, 0);
        
        if (validateInput()) {
            double gajiPokok = 0, bonus = 0;
            int jamKerja = 0;
            
            if (cmbJenisKontrak.getSelectedItem().equals("Tetap")) {
                gajiPokok = Double.parseDouble(txtGajiPokok.getText());
                bonus = Double.parseDouble(txtBonus.getText());
            } else {
                jamKerja = Integer.parseInt(txtJamKerja.getText());
            }
            
            boolean success = karyawanController.updateKaryawan(
                id,
                txtNip.getText(),
                txtNama.getText(),
                cmbJenisKontrak.getSelectedItem().toString(),
                gajiPokok, bonus, jamKerja
            );
            
            if (success) {
                clearForm();
                loadData();
            }
        }
    }
    
    private void hapusKaryawan() {
        int row = tblKaryawan.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
            return;
        }
        
        int id = (int) tblKaryawan.getValueAt(row, 0);
        boolean success = karyawanController.hapusKaryawan(id);
        
        if (success) {
            clearForm();
            loadData();
        }
    }
    
    private void cariKaryawan() {
        String keyword = txtCari.getText().trim();
        if (keyword.isEmpty()) {
            loadData();
        } else {
            // Implement search if needed
            JOptionPane.showMessageDialog(this, "Fitur pencarian: " + keyword);
        }
    }
    
    private void isiFormDariTabel(int row) {
        txtNip.setText(tblKaryawan.getValueAt(row, 1).toString());
        txtNama.setText(tblKaryawan.getValueAt(row, 2).toString());
        cmbJenisKontrak.setSelectedItem(tblKaryawan.getValueAt(row, 3).toString());
        
        if (tblKaryawan.getValueAt(row, 3).equals("Tetap")) {
            txtGajiPokok.setText(tblKaryawan.getValueAt(row, 4).toString());
            txtBonus.setText(tblKaryawan.getValueAt(row, 5).toString());
        } else {
            txtJamKerja.setText(tblKaryawan.getValueAt(row, 6).toString());
        }
    }
    
    private boolean validateInput() {
        if (txtNip.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIP tidak boleh kosong!");
            return false;
        }
        if (txtNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return false;
        }
        
        String jenis = cmbJenisKontrak.getSelectedItem().toString();
        if (jenis.equals("Tetap")) {
            try {
                Double.parseDouble(txtGajiPokok.getText());
                Double.parseDouble(txtBonus.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Gaji Pokok dan Bonus harus angka!");
                return false;
            }
        } else {
            try {
                Integer.parseInt(txtJamKerja.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Jam Kerja harus angka!");
                return false;
            }
        }
        return true;
    }
    
    private void clearForm() {
        txtNip.setText("");
        txtNama.setText("");
        txtGajiPokok.setText("");
        txtBonus.setText("");
        txtJamKerja.setText("");
        cmbJenisKontrak.setSelectedIndex(0);
        tblKaryawan.clearSelection();
    }
    
    // Method yang dipanggil oleh controller untuk update GUI
    public void tampilkanHasilPenggajian(String pesan) {
        txtAreaHasil.append(pesan);
        txtAreaHasil.setCaretPosition(txtAreaHasil.getDocument().getLength());
    }
    
    public void aktifkanTombolHitung(boolean aktif) {
        btnHitungGaji.setEnabled(aktif);
    }
    
    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) tblKaryawan.getModel();
    }
    
    // ============ AUTO-GENERATED ============
    // @SuppressWarnings("unchecked")
    private void initComponents() {
        // generate otomatis saat drag n drop
        
        tabPane = new javax.swing.JTabbedPane();
        panelData = new javax.swing.JPanel();
        panelGaji = new javax.swing.JPanel();
        
        // === Panel Data Components ===
        tblKaryawan = new javax.swing.JTable();
        JScrollPane scrollTabel = new javax.swing.JScrollPane(tblKaryawan);
        txtNip = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbJenisKontrak = new javax.swing.JComboBox<>(new String[]{"Tetap", "Paruh Waktu"});
        txtGajiPokok = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        txtJamKerja = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton("Tambah");
        btnUpdate = new javax.swing.JButton("Update");
        btnHapus = new javax.swing.JButton("Hapus");
        btnRefresh = new javax.swing.JButton("Refresh");
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton("Cari");
        
        // Labels
        JLabel lblNip = new JLabel("NIP:");
        JLabel lblNama = new JLabel("Nama:");
        JLabel lblJenis = new JLabel("Jenis Kontrak:");
        lblGajiPokok = new JLabel("Gaji Pokok:");
        lblBonus = new JLabel("Bonus:");
        lblJamKerja = new JLabel("Jam Kerja:");
        
        // === Panel Gaji Components ===
        JScrollPane scrollHasil = new javax.swing.JScrollPane();
        txtAreaHasil = new javax.swing.JTextArea();
        btnHitungGaji = new javax.swing.JButton("Hitung Semua Gaji (Multithread)");
        
        // Setting up the frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Penggajian Karyawan");
        setPreferredSize(new java.awt.Dimension(900, 600));
        
        pack();
        setLocationRelativeTo(null);
    }
    
    // Component declarations
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelGaji;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtJamKerja;
    private javax.swing.JTextField txtCari;
    private javax.swing.JComboBox<String> cmbJenisKontrak;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitungGaji;
    private javax.swing.JTextArea txtAreaHasil;
    private javax.swing.JLabel lblGajiPokok;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblJamKerja;
}
